// packages/frontend/angular/src/app/screens/home/components/card-form/card-form.component.ts
import { Component } from '@angular/core';
import { MatRadioChange } from '@angular/material/radio';

@Component({
  selector: 'app-card-form',
  templateUrl: './card-form.component.html',
  styleUrls: ['./card-form.component.scss']
})
export class CardFormComponent {
  radioValue = [
    {
      value: true,
      text: "Sim, sou maior de 18 anos",
    },
    {
      value: false,
      text: "Não",
    },
  ];

  onChange({ value }: MatRadioChange) {
    console.log(value)
  }
}

<mat-card class="card">
  <mat-form-field appearance="outline">
    <mat-label>E-mail</mat-label>
    <input matInput placeholder="Seu e-mail" />
  </mat-form-field>
</mat-card>
<mat-card class="card">
  <mat-form-field appearance="outline">
    <mat-label>Nome:</mat-label>
    <input matInput placeholder="Sua resposta" />
  </mat-form-field>
</mat-card>
<mat-card class="card">
  <mat-form-field appearance="outline">
    <mat-label>Telefone DDD+CELULAR 00 00000-0000</mat-label>
    <input matInput placeholder="Sua resposta" />
  </mat-form-field>
</mat-card>
<mat-card class="card">
  <mat-radio-group class="card__radio">
    <mat-radio-button
      *ngFor="let radio of radioValue"
      [value]="radio.value"
      (change)="onChange($event)"
      >{{ radio.text }}</mat-radio-button
    >
  </mat-radio-group>
</mat-card>
<mat-card class="card">
  <button mat-raised-button color="primary" class="card__button">
    Próxima
  </button>
</mat-card>

// src/screens/Home/CardForm.tsx
import {
  Card,
  FormControl,
  FormControlLabel,
  Radio,
  RadioGroup,
  TextField,
  Typography,
} from "@mui/material";

type CardFormProps = {
  name: string;
  onChange: (e: React.ChangeEvent) => void;
};

function CardEmail({ name, onChange }: CardFormProps) {
  return (
    <Card>
      <TextField
        fullWidth
        type="email"
        label="E-mail"
        placeholder="Seu e-mail"
        name={name}
        onChange={onChange}
      />
      {/* <Form.Text muted>Esta pergunta é obrigatória</Form.Text> */}
    </Card>
  );
}

function CardName({ name, onChange }: CardFormProps) {
  return (
    <Card>
      <TextField
        fullWidth
        type="text"
        label="Nome:"
        placeholder="Sua resposta"
        name={name}
        onChange={onChange}
      />
      {/* <Form.Text muted>Esta pergunta é obrigatória</Form.Text> */}
    </Card>
  );
}

function CardPhone({ name, onChange }: CardFormProps) {
  return (
    <Card>
      <TextField
        fullWidth
        type="text"
        label={
          <Typography variant="subtitle1">
            Telefone DDD+CELULAR <strong>00 00000-0000</strong>
          </Typography>
        }
        placeholder="Sua resposta"
        name={name}
        onChange={onChange}
      />
      {/* <Form.Text muted>Esta pergunta é obrigatória</Form.Text> */}
    </Card>
  );
}

function CardUnderAge() {
  return (
    <Card>
      <FormControl>
        <RadioGroup>
          <FormControlLabel
            value="overAge"
            control={<Radio />}
            label={
              <Typography variant="subtitle1">
                Sim, sou maior de 18 anos
              </Typography>
            }
          />
          <FormControlLabel
            value="underAge"
            control={<Radio />}
            label={<Typography variant="subtitle1">Não</Typography>}
          />
        </RadioGroup>
      </FormControl>
    </Card>
  );
}

export const CardForm = {
  Email: CardEmail,
  Name: CardName,
  Phone: CardPhone,
  UnderAge: CardUnderAge,
};
